Support pagingIo in mirror.net
dokan-dev/dokan-dotnet pull request #298
Opened 2022-03-10 15:15 UTC by TrabacchinLuigi

Little refactor to remove some warnings and tidy up

2022-03-10 15:16 UTC, TrabacchinLuigi commented
Should fix #294

2022-03-10 15:19 UTC, TrabacchinLuigi commented
also : is really an uint in unsafe mirror ? can really be that long? i mean, it's still 32bit, and makes more sense, but everywhere else an int32 is used

2022-03-12 03:13 UTC, Liryna requested changes

2022-03-12 03:13 UTC, Liryna commented on sample/DokanNetMirror/NativeMethods.cs
> +        [DllImport("kernel32.dll", SetLastError = true)]
return line missing

2022-03-12 03:13 UTC, Liryna commented
Thanks @TrabacchinLuigi for fixing the issue! Very appreciated 😎 

Just requested a small change before merge if thats not a problem

2022-03-12 09:22 UTC, TrabacchinLuigi commented
i've lot of changes right now, if it's not a problem i'll change that on next pull request

2022-03-12 09:23 UTC, TrabacchinLuigi commented
also, i was thinking some atributes are really not needed like marshaling boolean to boolean is the default choiche so no need to explicitly specify that

2022-03-12 10:04 UTC, TrabacchinLuigi commented
Dang since i've not made a feture branch i can't do another pull request, git is not my bread and butter, TFS is so much easier

2022-03-12 13:38 UTC, Liryna commented
Yeah when you work on the same branch due to your second commit based on another one that is also a PR, everything ends up in the same PR. That's fine if they are clean commit like yours 👍 
Thanks for taking care of the issue your reported!

2022-03-12 13:38 UTC, merged